#生成可执行文件
add_executable(logFormatterTest logFormatterTest.cc )
add_executable(LogAppenderTest LogAppenderTest.cc)
add_executable(ConditionTest ConditionTest.cc)
add_executable(ThreadTest ThreadTest.cc)
add_executable(AsynLogAppendTest AsynLogAppendTest.cc)
add_executable(LoggerTest LoggerTest.cc)
add_executable(ThreadPoolTest ThreadPoolTest.cc)
add_executable(TomlTest TomlTest.cc)
add_executable(ConfigTest ConfigTest.cc)
add_executable(DateTimeTest DateTimeTest.cc)
add_executable(UtilTest UtilTest.cc)
add_executable(EventLoopTest EventLoopTest.cc)
add_executable(TimerTest TimerTest.cc)

#链接动态库
target_link_libraries(logFormatterTest codebus)
target_link_libraries(LogAppenderTest codebus)
target_link_libraries(ConditionTest codebus)
target_link_libraries(ThreadTest codebus)
target_link_libraries(AsynLogAppendTest codebus)
target_link_libraries(LoggerTest codebus)
target_link_libraries(ThreadPoolTest codebus)
target_link_libraries(ConfigTest codebus)
target_link_libraries(DateTimeTest codebus)
target_link_libraries(UtilTest codebus)
target_link_libraries(EventLoopTest codebus)
target_link_libraries(TimerTest codebus)